name: easy_localization_lsp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

platforms:
  linux:
  windows:
  macos:

executables:
  easy_localization_lsp:

# Add regular dependencies here.
dependencies:
  lsp_server: ^0.3.2
  analyzer: ^6.11.0
  glob: ^2.1.2
  yaml: ^3.1.3
  uuid: ^4.5.1
  args: ^2.6.0
  diff_match_patch: ^0.4.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  lints: ^5.0.0
  test: ^1.24.0
